const TOGGLE_LOADING = 'TOGGLE_LOADING'; // 显示/隐藏加载
const RESET_MESSAGE = 'RESET_MESSAGE'; // 重置消息弹框数组
const LOAD_ALL_PATIENT_INFO = 'LOAD_ALL_PATIENT_INFO'; // 获取所有患者信息

export {
  TOGGLE_LOADING,
  RESET_MESSAGE,
  LOAD_ALL_PATIENT_INFO,
}
